### ISSUE TITLE
error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by delta9** [imgly/vesdk-android-demo#1]
> **Update for AndroidX**
Recently, we have come across a bug that, unfortunately, affects our VideoEditor SDK for Android if it is being updated with AndroidX. After some investigation on this matter, we found out that Google knows about it, but has not yet been able to solve it. In this reference (https://issuetracker.google.com/issues/119582492) you will currently find further information. However, we are currently working on a fix by establishing a new renderer for this matter. *Generally, we’d kindly ask you to refrain from updating to Android X at this stage*. We will keep you posted once our solution for the VideoEditor SDK allows you to use AndroidX without any constraints or concerns.

Hi,

It seems like Google has solved the **librsjni_androidx.so SIGSEGV** issue in their latest build tools version 29.0.2 release: https://developer.android.com/studio/releases/build-tools

But since SDK version 7 I'm running into a minor issue that won't let me compile using AndroidX:

> error: package android.support.annotation does not exist

It traces back to **IMGLYEvents.java**:

`
@android.support.annotation.Keep
public IMGLYEvents`

My dev environment looks like this:

Android Studio v3.5
Build Gradle: 3.5.0
Compile SDK 29
Build Tools 29.0.2
Kotlin Version: 1.3.41
PESDK: 7.0.2

Do you know how to solve this issue? I just purchased a license and would love to go ahead with the implementation.

Btw PESDK version 6.6 seems to work just fine now using AndroidX with build tools 29.0.2 - but it seems like the video editor isn't included there. 

Many thanks

@Btopp @svendvd @PhoenixRaw

**Comment by Btopp** [comment]
Hi,

Thanks for reaching out to us. **The problem is solved within v7.0.3**.
For future requests please use our Service Desk: https://imglysdk.atlassian.net/servicedesk/customer/portal/3

Thank you
